### ISSUE TITLE
Bip Api Baglantilari icin verilen mail adresi sorunlu

### ISSUE THREAD

**Issue by hakanzn** [Turkcell/BiP.AI#2]
Bip Api kullanici adi ve sifre almak icin verdiginiz bipresmihesap@turkcell.com.tr adresinde sorun var. Mail attigim gibi hata maili geliyor. Kontrol edip geri donus yaparsaniz sevinirim

hakanzn@gmail.com

**Comment by saacbip** [comment]
Merhabalar,
İletişim adresimiz [INFO-BIP-RESMI-HESAP@turkcell.com.tr](INFO-BIP-RESMI-HESAP@turkcell.com.tr) olarak güncellenmiştir.
